### PR TITLE
[FINCN-339] add-custom-validation-basedon-conf

### PR DESCRIPTION
**Pull request by fynmanoj**

### CODE REVIEW

**Comment by fynmanoj** [comment]
@awasum  could you please review this PR

**Comment by avikganguly01** [comment]
@josehernandezfintecheandomx : Can you review this PR?

**Comment by avikganguly01** [comment]
NotNull and NotBlank fields are made optional based on config (NotBlankBasedOnConfig, NotNullBasedOnConfig). This helps in onboarding zero KYC customers to be able to offer no frills accounts.

**Review by avikganguly01 — APPROVED** [review]

**Comment by edcable** [comment]
@avikganguly01 @fynmanoj could you link to the public issue or ticket that includes details on what functionality this pull request provides?

**Pull request merged**
