### PR TITLE
[FINCN-338] non-person-api-with-account

### PR DESCRIPTION
**Pull request by fynmanoj**

### CODE REVIEW

**Comment by fynmanoj** [comment]
@awasum  could you please have a look at this PR

**Comment by avikganguly01** [comment]
@josehernandezfintecheandomx : Can you review this PR?

**Comment by avikganguly01** [comment]
This supports automatically opening a savings account for a new customer when customer opts for it.

**Review by avikganguly01 — APPROVED** [review]

**Comment by edcable** [comment]
@avikganguly01 @fynmanoj thanks for committing this PR from the work being done with Cardano and NASASA for stokvel digitization. I see a brief description of what functionality this PR provides but can you please like to a public ticket that describes its requirements?

**Pull request merged**
