### PR TITLE
Document Customer API IN component-test module

### PR DESCRIPTION
**Pull request by Izakey**
Documented the Customer API IN the component-test module as per feedback on the mailing list.

### CODE REVIEW

**Comment by awasum** [comment]
Hey @Izakey 
I ran the tests and customerApiDocs test all pass but for some cassandra timeout problem some tests in IdentityAPIDoc tests are ignored.
Here is the error: com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9142] Timed out waiting for server response.

Did you ever face this problem? It might be due to my machine properties.

Apart from that, everything looks good so far.

**Comment by Izakey** [comment]
Hey @awasum 

ALL unit tests pass in my case, 15 in CustomerApiDocumentation and 9 in IdentificationsApiDocumentation. I don't face any timeout issues with Cassandra.

Any issues in the code with respect to style ?

**Comment by awasum** [comment]
Yes, Adjust your line start line for classes and methods to 2 lines not tabs. Just add another commit here and I will merge.

**Comment by awasum** [comment]
image
 adjust the highlighted setting in your IDE then reformat by going to Code -> Reformat Code while in the source file.

**Comment by awasum** [comment]
LGTM. Thanks @Izakey 

I am merging now.

**Pull request merged**
